### ISSUE TITLE
"Browse Videos" button implementation

### ISSUE THREAD

**Issue by BradleyCai** [dnxc/dnxc.github.io#8]
The button should scroll to the `video-list` div when clicked. Also perhaps there should be an indicator on the button that suggests that it will scroll you. That way it is not mistaken for a button that takes you to a webpage. 

Something like this:

![image](https://cloud.githubusercontent.com/assets/7998948/16538167/332e3d8c-3fd0-11e6-8147-cef08c18da5a.png)

**Comment by EvanJameson** [comment]
so as it stands currently things left to do for this issue are:

change the color of the current arrow

Fix the padding on the button
